### ISSUE TITLE
Media titles covered by thumbnail on mobile view

### ISSUE THREAD

**Issue by AustinWoetzel** [stakeordie/SecretWebsiteV2#14]
![Bug](https://user-images.githubusercontent.com/30289932/121374482-28b28000-c8fd-11eb-9bed-32a281291600.png)

**Comment by jsandovalg** [comment]
The issue is already solved.

![image](https://user-images.githubusercontent.com/81380326/121941200-d3fb7480-cd03-11eb-90f6-3dea22ca81a1.png)
