### ISSUE TITLE
Mobile View - Blog card with too large of space

### ISSUE THREAD

**Issue by AustinWoetzel** [stakeordie/SecretWebsiteV2#18]
Mobile view only: The text should either be larger or we should shrink the space. See attached photo.
![card](https://user-images.githubusercontent.com/30289932/121387771-2d306600-c908-11eb-8fdb-832c184f06a6.png)

**Comment by jsandovalg** [comment]
This issue has already done.

![image](https://user-images.githubusercontent.com/81380326/122132823-6d07b980-cdf0-11eb-9635-5fe17a307272.png)
