### ISSUE TITLE
Withdraw sSCRT-sUSDT(BSC)

### ISSUE THREAD

**Issue by BruNik11** [stakeordie/SecretWebsiteV2#37]
Hello everyone! I can't withdraw tokens from the pool. What is the problem?
<img width="517" alt="Снимок экрана 2021-06-20 в 11 24 49" src="https://user-images.githubusercontent.com/86170703/122667177-29c79500-d1ba-11eb-930c-331722b639a7.png">

**Comment by the-dusky** [comment]
Assume this was dealt with on a another channel
